### ISSUE TITLE
Functions not working

### ISSUE THREAD

**Issue by VitorTrin** [GoNZooo/vscode-aurora-gonzooo#1]
First of all, your theme is great, but when I installed, it looked different from the images.
The function calls are not being highlighted, and nor are the modules. Does it require another extension?

![image](https://user-images.githubusercontent.com/9387059/76427075-a00c0380-638a-11ea-83b6-e1f263549e9b.png)

**Comment by GoNZooo** [comment]
All you need is basic elixir syntax highlighting. It's indeed the case that the theme has indirectly changed over time.

The scopes for function calls at some point changed so as to annotate function calls as just "source", as far as I can tell:

![image](https://user-images.githubusercontent.com/1327032/76428739-bf208a80-63b6-11ea-9dac-4969f87e3ff5.png)

I think maybe the way modules are annotated was changed at some point as well, I don't know:

![image](https://user-images.githubusercontent.com/1327032/76429168-52f25680-63b7-11ea-98de-04d2326a6654.png)

In this example the module name is tagged as `variable.other.constant.elixir` and I think it used to be `entity.name.type.module.elixir`:

```
		{
			"name": "Elixir module",
			"scope": "entity.name.type.module.elixir",
			"settings": {
				"foreground": "#5f9cff",
				"fontStyle": "italic"
			}
		},
```

The token colors are set in `themes/AuroraGoNZooo-color-theme.json` and basically just say "For this scope set this token color". You can get a token overlay by opening the command palette and typing "scopes" and the only suggestion will be the command to open it.

Personally I'm not invested in Elixir anymore and for the most part I'm fine with the way these changes have ended up, so I'm probably not changing the theme, but I would suggest making your own fork and just changing these scopes to match the new ones.

The source one is of course a bit awkward since "source" is just your basic source text, but the module one is just that the scope for modules has changed, so you can just add the new exact scope for called modules and copy the `entity.name.type.module.elixir` token color for it. Be aware that the module name after `defmodule` is still scoped with the `entity.name.type.module.elixir` scope, though.

**Comment by VitorTrin** [comment]
Thanks for that quick reply and all the help for a project in a language you aren't invested anymore!

**Comment by GoNZooo** [comment]
So, I ended up making the module change and it should be up in v0.9.0 now, available on the marketplace.
